export const ROUTES = {
    home: '/',
    login: '/login',
    register: '/register',
    jobs: '/jobs',
    howItWorks: '/how-it-works',
    pricing: '/pricing',
    about: '/about',
    blog: '/blog',
    careers: '/careers',
    terms: '/terms',
    privacy: '/privacy',
    dashboard: '/dashboard',
    clientDashboard: '/dashboard/client',
    freelancerDashboard: '/dashboard/freelancer',
    adminDashboard: '/dashboard/admin',
    arbiterDashboard: '/dashboard/arbiter',
    createProject: '/projects/new',
    project: (id: string) => `/projects/${id}`,
    editProject: (id: string) => `/projects/${id}/edit`,
    profile: (id: string) => `/users/${id}`,
    settings: '/settings',
} as const